name: DevopsLab1

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Build Application
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: build/main.exe
  send_message:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: exe
          
      - name: ls 
        run: ls -la 
      
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          message: uploaded artifacts
          document: main.exe
