name: DevopsLab1

on:
  push:
    branches:
      - main
      
jobs:
  code_analyse:
    runs-on: windows-latest
    
    steps:
      - name: Repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Requirements
        run: pip install -r requirements.txt
        
      - name: Install Flake8 and PySnooper
        run: |
          pip install flake8
          pip install pysnooper
      
      - name: Code Style Check
        run: |
          flake8 main.py
      
      - name: Runtime Performance Check
        run: |
          python -m pysnooper main.py
  build:
    needs: code_analyse
    runs-on: windows-latest
    
    steps:
      - name: Build Application
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: build/main.exe
  send_message:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: exe
          
      - name: Arhive
        run: |
         7z a main.7z main.exe
          
      - name: ls 
        run: ls -la 
      
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          message: uploaded artifacts
          document: main.7z
